# Generated by Django 4.2.20 on 2025-06-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_age_profile_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followings',
            field=models.ManyToManyField(related_name='follwers', to='accounts.profile'),
        ),
    ]
