# Generated by Django 4.2.20 on 2025-05-04 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=10)),
                ('content', models.TextField()),
                ('date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
            ],
        ),
    ]
